### ISSUE TITLE
Issues with Item Stock Levels dashboard

### ISSUE THREAD

**Issue by Gwalior-84** [openmsupply/msupply-dashboard#108]
Figures on this [dashboard ](https://png.msupply.org:3000/d/vS1Fd2bZz/item-stock-levels?orgId=1&var-multiFacility=Hagen%20GH%20Main%20Store&var-facilityFilter=&var-codeStart=&var-code=All&var-nameCategory1=All&var-nameCategory1Level2=All&var-nameCategory1Level1=All&var-nameCategory2=Regional%20Hospital&var-nameCategory3=All&var-nameCategory4=All&var-nameCategory5=All&var-nameCategory6=All&var-organisation=All&var-mode=All&var-disabled=All&var-singleFacility=Hagen%20GH%20Main%20Store&var-itemCategory=All&var-itemCategoryLevel2=All&var-itemCategoryLevel1=All&var-itemCategory2=All&var-itemCategory3=All&var-venCategory=V&var-stockType=On%20essential%20drug%20list&var-stockLevel=All&var-itemFilter=&var-multiItem=All&var-singleItem=Adrenaline%20Injection,%201:1000,%201ml&var-nullString=NONE&var-storeTableName=store_categories&var-itemTableName=item_categories&var-facilityCount=1&var-itemCount=74&var-sqlRestriction=)appear not to be correct.

![image](https://user-images.githubusercontent.com/9062300/84616936-c2289b00-af10-11ea-85fb-897d9dcb5355.png)

For item 103600, live data:

SoH:  51,400 compared to 514.  I wonder if this is actually reporting (preferred) packs on hand instead of stock on hand?
![image](https://user-images.githubusercontent.com/9062300/84616508-86410600-af0f-11ea-92bf-7ff2b2222afc.png)

AMC(12) = 8,057 compared to 10,273.6
![image](https://user-images.githubusercontent.com/9062300/84616573-bf797600-af0f-11ea-9966-55a838273115.png)

Therefore, MoS should be 6.37 instead of 5.

Please explain.

**Comment by CarlosNZ** [comment]
> SoH: 51,400 compared to 514. I wonder if this is actually reporting (preferred) packs on hand instead of stock on hand?

Yes, it looks like it. We were using `available` from item_line, but I've changed it `stock_on_hand_total`. The number is closer to what you're expecting, but it's not always the same as `available x pack_size`. I'm not sure which one of these is more reliable -- anyone have any insight into that? (@mark-prins )

**Comment by mark-prins** [comment]
> anyone have any insight into that?

No, not me - I thought that `available` was a more reliable option, but I have no validation for that.

I've looked a little into the AMC and MOS questions too - the significant difference is that the dashboard is using the aggregator for its data. I've changed to use the `realAMC` element rather than `AMC` and this is closer - but still not close enough! 

As far as I can tell the aggregator version is including finalised customer invoices only, the value in the item tab is calculating and including confirmed as well as finalised. The aggregator is also including `stock_out` transaction lines, which the item tab isn't 

For a real answer - we'd have to ask @andreievg though.

**Comment by Gwalior-84** [comment]
@CarlosNZ  @mark-prins 

Thanks for changing it to `stock_on_hand_total`.  The quantities on unconfirmed CIs is `total` - `available`.  Using `total` or `available` should have little significant impact on the calculation, but I'd suggest using `available` as it is 'safer'.

From what you describe, the Aggregator version of AMC could be quite wrong for these reasons:  

1. mSupply desktop does not prompt for a user to finalise a CI to non-store customers.  It is a diligent officer indeed who bothers to finalise them.
2. `stock_out` transaction lines (what are these?  inv. adjustents?).  If they are inv. adjustments due to expiring on the shelf, except for fringe cases, they are distorting consumption upward, and shouldn't be included. Inv. Adj. out due to other valid reasons (damaged stock, theft, etc.) could be argued to be part of 'normal' consumption, but shouldn't be significant.  Excluding them is likely OK.  

I request that we change aggregator AMC to match the Item usage tab value.  Comments @craigdrown ?

**Comment by andreievg** [comment]
First check, monthlyConsumption, matches in this scenario

<img width="662" alt="Screen Shot 2020-06-15 at 9 40 55 PM" src="https://user-images.githubusercontent.com/26194949/84644871-de016080-af53-11ea-8efb-37241fc190ae.png">

Second check AMC calculation:

<img width="721" alt="Screen Shot 2020-06-15 at 9 45 19 PM" src="https://user-images.githubusercontent.com/26194949/84644892-e6f23200-af53-11ea-9a26-4a65f0b73e95.png">

Difference between Item form is it's taking one extra month (june-19) and dividing by 12. `aggregator_getLookBackDate` method btw, it's been like this from the start of aggregator.

My conclusion:
* Calculations should be aligned
* Aggregation code would probably be a cleaner place to make the change
* Since we take month as a whole, does it mean on 1st of every month there is (100/look back month)% decrease in AMC ? 8% for 12 month look back. 

For the last point, let's say we have 3 months look back period and we consume 1 quantity per month, at the end of the month we have 3 / 3 = 1amc, and the start of next month it's 2/3 = 0.7amc ?

**Comment by mark-prins** [comment]
ah. thanks @andreievg! nailed it.

![Screen Shot 2020-06-16 at 9 50 59 AM](https://user-images.githubusercontent.com/9192912/84710546-8a752e00-afb8-11ea-9618-b1425667fe50.png)

as you say, nothing to do with transaction status etc.
Changing the number of months being summed to 12, when dividing by 12, does align the numbers. but introduces the problem you highlight.

Issue raised for mSupply to work on this: https://github.com/sussol/msupply/issues/6383

**Comment by andreievg** [comment]
Btw, I think that issue, with the decrease in AMC at the start of the month applies to the Item form too.

**Comment by mark-prins** [comment]
yah, I think we need to address them both.
