### ISSUE TITLE
Item stock levels panel is not including all stores

### ISSUE THREAD

**Issue by Gwalior-84** [openmsupply/msupply-dashboard#117]
Report:  https://png.msupply.org:3000/d/n9vlqBZMk/item-stock-levels-ncd?orgId=1&var-multiFacility=All&var-facilityFilter=&var-codeStart=&var-code=All&var-nameCategory1=All&var-nameCategory1Level2=All&var-nameCategory1Level1=All&var-nameCategory2=All&var-nameCategory3=All&var-nameCategory4=All&var-nameCategory5=All&var-nameCategory6=All&var-organisation=All&var-mode=All&var-disabled=All&var-singleFacility=AMGH%20Main%20store&var-itemCategory=All&var-itemCategoryLevel2=All&var-itemCategoryLevel1=All&var-itemCategory2=All&var-itemCategory3=All&var-venCategory=All&var-stockType=On%20essential%20drug%20list&var-stockLevel=All&var-itemFilter=&var-multiItem=All&var-singleItem=Bupivacaine%20Injection,%200.5%25%20Heavy,%204%20ml%20&var-nullString=NONE&var-storeTableName=store_categories&var-itemTableName=item_categories&var-facilityCount=203&var-itemCount=136&var-sqlRestriction=&var-restrictByCategoryLevel=Western%20Highlands

Expected behaviour:  should include all stores with Category1 Level2 = `NCD`.  However, it includes only two of the stores where Category1 Level2 = `Western Highlands`

**Comment by CarlosNZ** [comment]
@Gwalior-84 that url you posted has `var-nameCategory1Level2=All`, so will be showing all from that Category. 

The nameCategory1Level2 filter was hidden, so I've made it visible in the Filter bar now. Let me know if that works correctly for you.

**Comment by Gwalior-84** [comment]
Thanks for looking in to this @CarlosNZ .  I need to understand how the filtering / selection works and how to control it.  I am expecting that all of the filters will apply.  In this example, if `var-nameCategory1Level2=All` and `var-restrictByCategoryLevel=NCD`, then it will only show results for **both** are true.  Is that right?

In the example here, the text in the URL includes `=&var-restrictByCategoryLevel=Western%20Highlands` but in the panel itself, this is set to `NCD`:

![image](https://user-images.githubusercontent.com/9062300/86667637-2c76bc00-c035-11ea-9aa9-22439e5372db.png)

However, when I look at the JSON I can see that **Western Highlands** is included somehow:

![image](https://user-images.githubusercontent.com/9062300/86667985-88d9db80-c035-11ea-9a9f-e466a9f33850.png)

Can you point me to instructions on how to fix this?

**Comment by CarlosNZ** [comment]
> I am expecting that all of the filters will apply. In this example, if `var-nameCategory1Level2=All` and `var-restrictByCategoryLevel=NCD`, then it will only show results for **both** are true. Is that right?

That new filter `restrictByCategoryLevel` just creates the dropdown list at the top, but it isn't actually tied to any database query. We'd need to include it in the "Province" query like so:
```
SELECT category1_level2 FROM $storeTableName
WHERE category1_level2 = '$restrictByCategoryLevel'
ORDER BY category1_level2 = '$nullString' desc, category1_level2
```

If we're wanting to implement these restrictions on a per-dashboard basis, it'd probably be better to hard-code the restrictions into the filter queries, otherwise someone could look at a different set of results just by changing the URL (as you're effectively doing above with "Western Highlands", even though the `restrictByCategoryLevel` only has 'NCD' available).


`However, when I look at the JSON I can see that Western Highlands is included somehow`

The JSON shows the current state as well as the available options. Once you select from the filter, it'll change to 'NCD' (as it's the only option), but that filter was hidden, so you couldn't select. Hence, better to hard-code these restrictions into the queries. so you'd just make the "Province" filter query:
```
SELECT category1_level2 FROM $storeTableName
WHERE category1_level2 = 'NCD'
ORDER BY category1_level2 = '$nullString' desc, category1_level2
```

I've gone ahead and applied that query as described so you can see how it will work. Now only "NCD" is available from the Province filter. Is this what you're trying to achieve?
