### ISSUE TITLE
Records not appearing in Aggregator table

### ISSUE THREAD

**Issue by Gwalior-84** [openmsupply/msupply-dashboard#157]
This report is failing:

https://png.msupply.org:3000/d/XJQ3b9pGz/item-stock-levels-shp?orgId=1&var-provinceRestriction=Southern%20Highlands&var-multiFacility=All&var-facilityFilter=&var-codeStart=&var-code=All&var-nameCategory1=All&var-nameCategory1Level2=All&var-nameCategory1Level1=All&var-nameCategory2=All&var-nameCategory3=All&var-nameCategory4=All&var-nameCategory5=All&var-nameCategory6=All&var-organisation=All&var-mode=All&var-singleFacility=Epeanda%20ART&var-itemCategory=All&var-itemCategoryLevel2=All&var-itemCategoryLevel1=All&var-itemCategory2=All&var-itemCategory3=All&var-venCategory=All&var-stockType=All&var-stockLevel=All&var-itemFilter=&var-masterList=ALL%20Items&var-multiItem=All&var-singleItem=Abacavir%20(ABC),%20300mg%20Tablets&var-nullString=NONE&var-storeTableName=store_categories&var-itemTableName=item_categories&var-facilityCount=2&var-itemCount=4710

@CarlosNZ obervation:

Regarding Southern Highlands — it seems that the information is simply not in the aggregator table —it’s being exported and displayed correctly, there’s just no aggregator info for those two stores. Maybe make an issue for that on the mSupply github (or a suppor request if you think it’s specific to PNG), I don’t think there’s anything we can do on the dashboard itself at this point.

Possibly clue (from somebody who doesn't understand how the dashboard reports actually work):  This shows the tables being exported:

![image](https://user-images.githubusercontent.com/9062300/97824896-4ab5a580-1d11-11eb-8149-b567c8ce4540.png)

Most of these name_category1 fields are used as filters in dashboard reports.  name_category1_level1 is the Province, e.g. Southern Highlands.

**Comment by mark-prins** [comment]
@Mai21 would you have time to look into this one?

**Comment by Mai21** [comment]
@mark-prins 
This issue seems like the one before we created new dashboards in December 2020.
New dashboard for Southern Highlands is https://png.msupply.org:3000/d/E0TB-B1Gz/shp-item-stock-levels-and-sync-stats?orgId=1 and their aggregator data is existing on Grafana now. 

Is it correct, @Gwalior-84 ?

**Comment by CarlosNZ** [comment]
Yeah, just to chime in here -- I think *most* of the problems with missing aggregation data in the PNG dashboard tables ended up being due to using `JOIN` rather than `LEFT JOIN` in the query (hence if any of the joined fields were missing, the whole row woudn't appear). I think I fixed most of the problem ones, but there might still be a few panels that need this fix.

**Comment by Gwalior-84** [comment]
Yes @Mai21 that new dashboard is working, and what's more, that original link appears not to work.  At this stage, let's close it.

**Comment by mark-prins** [comment]
Thanks all 😄
